global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@example.com'
  smtp_auth_username: 'helpingrobot617@gmail.com'
  smtp_auth_password: 'your_app_password'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email.team'

receivers:
  - name: 'email.team'
    email_configs:
      - to: 'helpingrobot617@gmail.com'
        headers:
          Subject: "Alert: {{ .CommonLabels.alertname }}"
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']